name: Inventory Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'rag_data_source/python-inventory/**'

jobs:
  security-and-test:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./rag_data_source/python-inventory

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety flake8 pytest

    - name: Safety Check
      run: safety check

    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      run: pytest

    - name: Docker Build
      run: docker build . -t inventory-service:latest
